version: '3.3'
services:
  app:
    #build: . # build from Dockerfile
    image: fahrrader/lab4_pyapp
    command: python3 main.py # command to start container=
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - 80:8080 # host : container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./media:/www/media
    depends_on:
      - app

  db:
    image: redis:alpine
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    hostname: redis